### PR TITLE
feat(cmd): Support custom cache

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <gaoce@caicloud.io>

**What this PR does / why we need it**:

We keep the cache and config.json in `$HOME/.ormb/` by default. But users can customize it using `rootPath` in `$HOME/.ormb/config.yaml`

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ddysher** [comment]
bot will not automatically add /approve label now? @bbbmj

**Comment by gaocegege** [comment]
/

**Pull request merged**
