### PR TITLE
feat(cmd): support plain HTTP

### PR DESCRIPTION
**Pull request by simon-cj**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @gaocegege 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gaocegege** [comment]
Fix #18

**Comment by ddysher** [comment]
image

@simon-cj  don't leave these descriptions empty
- You can remove `What this PR does / why we need it:` if it's not useful or add some descriptions
- Add issue link under `Which issue(s) this PR is related to (optional, link to 3rd issue(s)):`

**Comment by simon-cj** [comment]
OK， get it.
I‘am sorry to reply too late，thanks for you suggestion.

**Comment by ddysher** [comment]
Nothing to sorry about, just follow the best practice :)
> I‘am sorry to reply too late，thanks for you suggestion.

**Pull request merged**
